### ISSUE TITLE
The ES256 algorithm is not allowed or supported by the JWS signer: Supported algorithms: [ES384]

### ISSUE THREAD

**Issue by cassiusvm** [mjeffrey/spring-security-oauth2-restclient-interceptor#3]
Hello,

I did fork your project,  here it is: https://github.com/cassiusvm/spring-security-oauth2-restclient-interceptor

I am using Spring Boot 3.3.0 and Java 21.

I have the error below.

Please, help me to find the root cause.

Thanks in advance.

**P.S.: how to import my-realm?**

The error:
`
2024-06-17T14:01:30.448-03:00 DEBUG 57488 --- [nio-8081-exec-1] o.s.security.web.FilterChainProxy        : Secured GET /restClientPassword
2024-06-17T14:01:30.450-03:00 DEBUG 57488 --- [nio-8081-exec-1] o.s.web.servlet.DispatcherServlet        : GET "/restClientPassword", parameters={}
2024-06-17T14:01:30.452-03:00 DEBUG 57488 --- [nio-8081-exec-1] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to com.example.springsecurityrestclient.TestController#restClientPassword()
2024-06-17T14:01:30.462-03:00  INFO 57488 --- [nio-8081-exec-1] c.e.s.TestController                     : restClientPassword called
2024-06-17T14:01:30.495-03:00 DEBUG 57488 --- [nio-8081-exec-1] o.s.web.client.RestTemplate              : HTTP POST http://localhost:8080/realms/my-realm/protocol/openid-connect/token
2024-06-17T14:01:30.500-03:00 DEBUG 57488 --- [nio-8081-exec-1] o.s.web.client.RestTemplate              : Accept=[application/json, application/*+json]
2024-06-17T14:01:30.501-03:00 DEBUG 57488 --- [nio-8081-exec-1] o.s.web.client.RestTemplate              : Writing [{grant_type=[client_credentials], client_id=[my-client]}] as "application/x-www-form-urlencoded;charset=UTF-8"
2024-06-17T14:02:00.005-03:00  INFO 57488 --- [   scheduling-1] c.e.s.CronService                        : cronJob called
2024-06-17T14:02:00.072-03:00 ERROR 57488 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

org.springframework.security.oauth2.jwt.JwtEncodingException: An error occurred while attempting to encode the Jwt: Failed to sign the JWT -> The ES256 algorithm is not allowed or supported by the JWS signer: Supported algorithms: [ES384]
	at org.springframework.security.oauth2.jwt.NimbusJwtEncoder.serialize(NimbusJwtEncoder.java:152) ~[spring-security-oauth2-jose-6.3.0.jar:6.3.0]
	at org.springframework.security.oauth2.jwt.NimbusJwtEncoder.encode(NimbusJwtEncoder.java:111) ~[spring-security-oauth2-jose-6.3.0.jar:6.3.0]
`

**Comment by cassiusvm** [comment]
I solved the issue:
```
    private static KeyPair generateEcKey() {
        Security.setProperty("crypto.policy", "unlimited");
        BouncyCastleProvider bouncyCastleProvider = new BouncyCastleProvider();
        Security.addProvider(bouncyCastleProvider);
        KeyPairGenerator keyPairGenerator = KeyPairGenerator.getInstance("EC", bouncyCastleProvider.getName());
        keyPairGenerator.initialize(new ECGenParameterSpec("secp256r1"));
        return keyPairGenerator.generateKeyPair();
    }

**Comment by cassiusvm** [comment]
Indeed, it doesn't need BouncyCastle Provider, just: keyPairGenerator.initialize(new ECGenParameterSpec("secp256r1"))
